image: node:latest

stages:
  - build
  - run


frontend_starting:
  stage: run
  script:
    - npm start
  artifacts:
    paths:
      - node_modules/

frontend_test:
  stage: run
  script:
    - echo "Hallo test!"