stages:
  - build
  - test

build:
  stage: build
  image: semester-3-project-frontend
  script: 
    - echo "Start building App"
    - npm install
    - npm build
    - echo "Build successfully!"

test:
  stage: test
  image: semester-3-project-frontend
  script:
    - echo "Testing App"
    - npm install
    - CI=true npm test
    - echo "Test successfully!"
