services:
  frontend:
    build:
      context: "./frontend/studenten-app"
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend:
    build:
      context: "./backend/StudentenAppBackend"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"