name: Backend applicatie

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  static_code_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B verify pmd:pmd
    - uses: jwgmeligmeyling/pmd-github-action@master
      with:
        path: backend/StudentenAppBackend/reports/pmd-report.xml
      
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build/push docker image
        working-directory: ./backend/StudentenAppBackend
        run: |
          echo "${{ secrets.dockerPW }}" | docker login -u "ninadw34" --password-stdin
          docker image build -t ninadw34/backend-app-springboot .
          docker push ninadw34/backend-app-springboot
