name: Backend applicatie

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  static_code_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build Maven
      run: mvn -B --file backend/StudentenAppBackend/pom.xml verify pmd:pmd
    - uses: jwgmeligmeyling/pmd-github-action@master
      with:
        path: '**/pmd.xml'
      
  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v2
      - name: Set up actions JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run unittests
        run: mvn -B package --file backend/StudentenAppBackend/pom.xml -DskipTests
      - name: Test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unittest reports
          path: backend/StudentenAppBackend/target/surefire-reports/TEST-*.xml
          reporter: java-junit
          testFormat: "junit"
          testPaths: "**/surefire-reports/*.xml"

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build/push docker image
        working-directory: ./backend/StudentenAppBackend
        run: |
          echo "${{ secrets.dockerPW }}" | docker login -u "ninadw34" --password-stdin
          docker image build -t ninadw34/backend-app-springboot .
          docker push ninadw34/backend-app-springboot
