name: Backend applicatie

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  static_code_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: pmd/pmd-github-action@v1
      with:
        rulesets: 'ruleset.xml'
      
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build/push docker image
        working-directory: ./backend/StudentenAppBackend
        run: |
          echo "${{ secrets.dockerPW }}" | docker login -u "ninadw34" --password-stdin
          docker image build -t ninadw34/backend-app-springboot .
          docker push ninadw34/backend-app-springboot
