name: Backend applicatie

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  static_code_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: pmd
        uses: rtjl/pmd-analyzer-action@v0.1.5-alpha
        with:
          pmd-version: '6.31.0'
          source-path: './src'
          rule-path: './PMD.Rules.xml'
      
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build/push docker image
        working-directory: ./backend/StudentenAppBackend
        run: |
          echo "${{ secrets.dockerPW }}" | docker login -u "ninadw34" --password-stdin
          docker image build -t ninadw34/backend-app-springboot .
          docker push ninadw34/backend-app-springboot
