name: Backend applicatie

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: mvn -B test --file backend/StudentenAppBackend/pom.xml
        
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build/push docker image
        working-directory: ./backend/StudentenAppBackend
        run: |
          echo "${{ secrets.dockerPW }}" | docker login -u "ninadw34" --password-stdin
          docker image build -t ninadw34/backend-app-springboot .
          docker push ninadw34/backend-app-springboot
