name: Static code analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  static_code_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: "17"
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: PMD Report
        run: mvn -B verify pmd:pmd
      - uses: jwgmeligmeyling/pmd-github-action@master
        with:
          path: "**/pmd-report.xml"
      - name: PMD Check
        run: mvn -B verify pmd:check
