name: Static code analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  static_code_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: "17"
      - uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: PMD Report
        run: mvn pmd:pmd
      - name: pmd results
        uses: actions/upload-artifact@v1
        with:
          name: pmd_results
          path: backend/StudentenAppBackend/reports/pmd-report.xml
